name: Build & Deploy AWS Lambda Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Upload to S3 and Deploy to lambda
        env:
          release_bucket: chatbot-trail-deploy
          release_bucket_uri: s3://chatbot-trail-deploy
          release_id: ${{ format('chatbot-trail-{0}.zip', github.sha) }}
        run: |
          mkdir dependencies
          pip install -t dependencies -r requirements.txt
          cp -r templates dependencies
          echo building number $release_id
          zip --quiet -r $release_id dependencies
          zip $release_id -u main.py
          aws s3 cp $release_id $release_bucket_uri
          aws lambda update-function-code --function-name chatgpt --s3-bucket release_bucket_uri --s3-key release_id
